apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: caikit-tgis-serving-main
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: caikit-tgis-serving-main
    app.kubernetes.io/part-of: caikit-tgis-serving
  name: caikit-tgis-serving-main2yr4
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: caikit-tgis-serving-main
    weight: 100
status: {}
